services: 
   kroki: 
     image: yuzutech/kroki:0.24.1 
  
   scrape-and-plot: 
     build: . 
<<<<<<< HEAD
     image: ghcr.io/hochfrequenz/ebd_toolchain:v0.13.3-rc2
=======
     image: ghcr.io/hochfrequenz/ebd_toolchain:v0.13.3-rc
>>>>>>> ci/toolchain-FV2504
     # If you run into 'manifest unknown' during docker pull, try replacing `:latest` with `:v1.2.3`. 
     # where v1.2.3 is the latest version of the GHCR image, which can be found here: 
     # https://github.com/Hochfrequenz/ebd_toolchain/pkgs/container/ebd_toolchain 
     volumes: 
       - ${EBD_DOCX_FILE}:/container/ebd.docx 
       - ${OUTPUT_DIR}:/container/output 
     # we need to set the KROKI_HOST and KROKI_PORT to the host and port of the kroki service 
     # this is configurable here, but it does not need to be changed if the kroki service is named "kroki" 
     environment: 
       KROKI_PORT: "8000" 
       KROKI_HOST: "kroki" 
     # the .env file contains the parameter which the user can set 
     env_file: 
       - path: .env 
         required: true  # default is true
