name: EDI@Energy auto-approve / -merge
on: pull_request

jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    if: >-
      ${{
        github.actor == 'hf-kklein' &&
        startsWith(github.event.pull_request.title, 'EDI@Energy Changes')
      }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
