name: Auto Approve and Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check author, approve and merge
        uses: actions/github-script@v5
        with:
          # the user hf-kklein is the issuer of the PUSH_TOKEN used in the mirror.yml
          script: |
            const { author } = context.payload.pull_request;
            if (author.login === 'hf-kklein')
              const pullRequestNumber = context.payload.pull_request.number;
              const repository = context.repo.repo;
              const owner = context.repo.owner;
              
              // Approve the pull request
              await github.rest.pulls.createReview({
                owner,
                repo: repository,
                pull_number: pullRequestNumber,
                event: 'APPROVE'
              });

              // Merge the pull request
              await github.rest.pulls.merge({
                owner,
                repo: repository,
                pull_number: pullRequestNumber,
                // Optional parameters like commit title, message, merge method can be added here
              });
            }
