name: Run kohlrAHBi
on:
  push: {}
jobs:
  check:
    name: Parse the Docx Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          path: edi_energy_mirror
          lfs: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kohlrahbi
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MRAHB_PUSH_TOKEN }}
          repository: Hochfrequenz/machine-readable_anwendungshandbuecher
          path: machine-readable_anwendungshandbuecher
          lfs: true
      - name: Run Extraction (Current)
        run: |
          kohlrahbi --input_path edi_energy_mirror/edi_energy_de/current --output_path ./machine-readable_anwendungshandbuecher/FV2304
      - name: Run Extraction (Future)
        run: |
          kohlrahbi --input_path edi_energy_mirror/edi_energy_de/future --output_path ./machine-readable_anwendungshandbuecher/FV2310
      - name: Push flat AHBs to machine-readable_anwendungshandbuecher
        uses: peter-evans/create-pull-request@v4
        with:
           path:  machine-readable_anwendungshandbuecher
           title: EDI@Energy KohlrAHBi Changes ${{ steps.current-time.outputs.formattedTime }}
           token: ${{ secrets.MRAHB_PUSH_TOKEN }} # this token expires on 2024-02-15
           # token with repo scope
           # https://github.com/Hochfrequenz/edi_energy_mirror/settings/secrets/actions/MRAHB_PUSH_TOKEN
           branch: update-${{ steps.current-time.outputs.formattedTime }}
