name: Run kohlrAHBi
on:
  push:
    branches:
      - master
    paths:
      - 'edi_energy_de/**/*.docx'
      - 'dependencies/kohlrahbi-requirements.txt'
jobs:
  check:
    name: Parse the Docx Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scrapepath: ["--input-path edi_energy_mirror/edi_energy_de/current --output-path ./machine-readable_anwendungshandbuecher/FV2310", "--input-path edi_energy_mirror/edi_energy_de/future --output-path ./machine-readable_anwendungshandbuecher/FV2404"]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          path: edi_energy_mirror
          lfs: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: "edi_energy_mirror"
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies/kohlrahbi-requirements.txt
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MRAHB_PUSH_TOKEN }}
          repository: Hochfrequenz/machine-readable_anwendungshandbuecher
          path: machine-readable_anwendungshandbuecher
          lfs: true
      - name: Run Extraction
        run: |
          kohlrahbi ${{ matrix.scrapepath }} --file-type flatahb --file-type csv --file-type xlsx
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
      - name: Push flat AHBs to machine-readable_anwendungshandbuecher
        uses: peter-evans/create-pull-request@v6
        with:
           path:  machine-readable_anwendungshandbuecher
           title: EDI@Energy KohlrAHBi Changes ${{ steps.current-time.outputs.formattedTime }}
           token: ${{ secrets.MRAHB_PUSH_TOKEN }} # this token expires on 2025-02-13
           # token with repo scope
           # https://github.com/Hochfrequenz/edi_energy_mirror/settings/secrets/actions/MRAHB_PUSH_TOKEN
           branch: update-${{ steps.current-time.outputs.formattedTime }}
           reviewers: hf-krechan
           assignees: hf-krechan
