name: Run kohlrAHBi
on:
  push: {}
jobs:
  check:
    name: Parse the Docx Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          path: edi_energy_mirror
          lfs: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kohlrahbi
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MRAHB_PUSH_TOKEN }}
          repository: Hochfrequenz/machine-readable_anwendungshandbuecher
          path: machine-readable_anwendungshandbuecher
          lfs: true
      - name: Run Extraction
        run: |
          kohlrahbi --input_path edi_energy_mirror/edi_energy_de/current --output_path ./machine-readable_anwendungshandbuecher/FV2210/UTILMD/ --pruefis 11039
      #- name: Commit changes
      #  run: |
      #    git config --global user.name "automatic update"
      #    git config --global user.email "your-email@example.inv"
      #    git add .
      #    git commit -m "EDI@Energy KohlrAHBi Changes ${{ steps.current-time.outputs.formattedTime }}"
      - name: Push flat AHBs to machine-readable_anwendungshandbuecher
        #uses: actions/github-script@v6
        #with:
        #  github-token: ${{ secrets.MRAHB_PUSH_TOKEN }} # this token expires on 2024-02-15
        #  script: |
        #    // Push the branch to the repository
        #    await github.rest.git.createRef({
        #       owner: 'Hochfrequenz',
        #       repo: 'machine-readable_anwendungshandbuecher',
        #       ref: 'refs/heads/my-feature-branch',
        #       sha: context.sha
        #    });
        #    const { data } = await github.rest.pulls.create({
        #      owner: 'Hochfrequenz',
        #      repo: 'machine-readable_anwendungshandbuecher',
        #      title: 'My Pull Request',
        #      head: 'my-feature-branch',
        #      base: 'main',
        #      body: 'This is my pull request description.'
        #    });
        #    console.log(`Created pull request #${data.number}: ${data.html_url}`);

        uses: peter-evans/create-pull-request@v4
        with:
           path:  machine-readable_anwendungshandbuecher
           title: EDI@Energy KohlrAHBi Changes ${{ steps.current-time.outputs.formattedTime }}
           token: ${{ secrets.MRAHB_PUSH_TOKEN }} # this token expires on 2024-02-15
           # token with repo scope
           # https://github.com/Hochfrequenz/edi_energy_mirror/settings/secrets/actions/MRAHB_PUSH_TOKEN
           branch: update-${{ steps.current-time.outputs.formattedTime }}
