name: Pull Documents from edi@energy
on:
  push: { }
  schedule:
    - cron: '29 14 * * 6'
jobs:
  check:
    name: Read all AHBs and Extract Conditions
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Extraction
        run: |
          python download_and_post_process.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        
