name: Pull Documents from edi@energy
on:
  schedule:
    - cron: '01 8,11,17 * * *'
  push:
    paths:
      - 'dependencies/mirror-requirements.txt'
      - '.github/workflows/mirror.yml'
jobs:
  check:
    name: Read all AHBs and Extract Conditions
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies/mirror-requirements.txt
      - name: Run Extraction
        run: |
          python download_and_post_process.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: EDI@Energy Changes ${{ steps.current-time.outputs.formattedTime }}
          token: ${{ secrets.PUSH_TOKEN }} # expires 2025-01-16
          # https://github.com/Hochfrequenz/edi_energy_mirror/settings/secrets/actions/PUSH_TOKEN
          # Github Token with repo scope
          branch: update-${{ steps.current-time.outputs.formattedTime }}
          reviewers: hf-krechan
          assignees: hf-krechan
          # the reality check shows, that the reviewers and assignees don't care about the PR
          # so there's a nother GH action which just auto-approves all PRs created by this workflow
          # => autoapprove.yml
          
