name: Pull Documents from edi@energy
on:
  schedule:
    - cron: '01 8,11,17 * * *'
jobs:
  check:
    name: Read all AHBs and Extract Conditions
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Extraction
        run: |
          python download_and_post_process.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: EDI@Energy Changes ${{ steps.current-time.outputs.formattedTime }}
          token: ${{ secrets.PUSH_TOKEN }} # expires 2024-01-15
          # https://github.com/Hochfrequenz/edi_energy_mirror/settings/secrets/actions/PUSH_TOKEN
          # Github Token with repo scope
          branch: update-${{ steps.current-time.outputs.formattedTime }}
          
